spring:
  application:
    name: Spring Boot Order Service Application
  data:
    mongodb:
      uri: ${mongodb-uri}
      database: "online_store"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d8rm3bg4cwywnjin.eu.auth0.com/
  cloud:
    function:
      definition: product-availability-updated
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
      bindings:
        product-availability-updated-in-0:
          destination: product-events
          group: my-consumer-group
          content-type: application/json

server:
  port: 8081