spring:
  application:
    name: Spring Boot Order Service Application
  data:
    mongodb:
      uri: ${mongodb-uri}
      database: "online_store"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d8rm3bg4cwywnjin.eu.auth0.com/
  kafka:
    consumer:
      topic: product-availability-updated-events
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8081